#
###################################
# Site wide configuration
####################################
#
title: Ilya Manin
email: bkmzvf@gmail.com
description: "software engineer"
url: https://xamut.github.io
include: [_pages]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Novosibirsk
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ilya Manin
  gravatar_url: https://gravatar.com/avatar/df690ae5543371ec4cb3af5bcf5018b2?s=200
  job: "software engineer"
  bio:
  email: bkmzvf@gmail.com
  twitter: xamut
  facebook: ilya.a.manin
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: xamut
  gitlab: xamut
  linkedin: xamut
  skype: xamut_
  telegram: xamut
  instagram: xamut
  lastfm: xamut
